// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adgqwzazspqhpdmtwhkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ3F3emF6c3BxaHBkbXR3aGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODAxMzQsImV4cCI6MjA2MTk1NjEzNH0.74hAC36hhg2vdhBz8hl-cGT3eqNlT4PkpodbpqfI7_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);